Issue #81: Fix case insensitivity bug
microsoft/kiota-abstractions-dotnet pull request #103
Opened 2023-06-29 12:07 UTC by ichbinsteffen

In [Issue #81](https://github.com/microsoft/kiota-abstractions-dotnet/issues/81) @seruminar described why URIs don't contain query parameters when the models they are derived from have pascal cased property names.

Here is my short take on the problem:
    - When the URL template contains query parameters with upper case first letters and the QueryParameters contains them in lowerCase (because they are added using x.Name.ToFirstCharacterLowerCase()) then the names are not matched and the resulting URI does not contain the parameters.
    - When in the URI getter the parameters are actually set using uriTemplate.SetParameter then in the dictionary the casing does not match, and therefore they are silently failing to be set.
    - The UriTemplate ctor contains the optional setting (caseInsensitiveParameterNames) to use a case insensitive dictionary. IMHO this is the best solution because then it does not matter what kind of casing patterns the API models have.

The alternative solution to this would be to change AddQueryParameters where
`x.Name.ToFirstCharacterLowerCase()` is called for each parameter. Lowercasing the first char is what causes this bug in the first place. The strings in the dictionary would naturally match the API model from which they are collected. 

What do you think would be the better fix?

2023-07-01 20:30 UTC, baywet requested changes
Thanks for the contribution @ichbinsteffen 

Would you please mind adding:
- an entry to the changelog (patch, date to Monday)
- a unit test
- bump the version in the csproj

2023-07-03 11:20 UTC, ichbinsteffen commented
> @ichbinsteffen please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> [...]

Currently my legal department is looking into this. They will let me know soon if I can give a license acceptance.

2023-07-03 11:23 UTC, baywet approved these changes
Thanks for making the changes. @andrueastman for final review and merge

2023-07-03 13:25 UTC, andrueastman approved these changes

2023-07-03 13:29 UTC, baywet commented
@andrueastman I just realized the CLA was not a required check on this repo main branch policy. I think this is due to the recent migration. Can you double check the other Kiota dotnet repos please?

2023-07-04 06:27 UTC, andrueastman commented
> @andrueastman I just realized the CLA was not a required check on this repo main branch policy. I think this is due to the recent migration. Can you double check the other Kiota dotnet repos please?

Thanks for pointing this @baywet. Will look into this and resolve.

2023-07-04 07:49 UTC, ichbinsteffen commented
> @andrueastman I just realized the CLA was not a required check on this repo main branch policy. I think this is due to the recent migration. Can you double check the other Kiota dotnet repos please?

Nonetheless, our legal department allowed me to sign it. So I'll sign it in a dedicated comment.

2023-07-04 07:50 UTC, ichbinsteffen commented
@microsoft-github-policy-service agree company="Init Innovation In Traffic Systems SE"

2023-07-04 07:50 UTC, merged